language: cpp

# Use container-based infrastructure
sudo: required
services:
  - docker

os:
  - linux

compiler:
  - gcc
  - clang

env:
  global:
    - GTEST_INSTALL=${TRAVIS_BUILD_DIR}/install-gtest
    - PLOUD_INSTALL=${TRAVIS_BUILD_DIR}/install-ploud
    - CI_NODE_TOTAL=2

# This results in a 2×2 build matrix.
# Where the variables are: os / compiler

addons:
  apt:
    sources: ['boost-latest']
    packages:
    - scons
    - libboost1.55-all-dev
    - libsndfile1-dev
    - libqt4-dev

cache:
  # Caching Ubuntu packages
  apt: true

install:
  - ./tools/travis/install_dependencies.sh

after_install:
  # Get test ressources
  - wget https://tech.ebu.ch/files/live/sites/tech/files/shared/testmaterial/ebu-loudness-test-setv04.zip --no-check-certificate
  - unzip ebu-loudness-test-setv04.zip
  - export EBU_LOUDNESS_TEST_SET_PATH=`pwd`

script:
  - export QTDIR=/usr/share/qt4
  # Build and run tests
  - scons -j${CI_NODE_TOTAL} --mode=release --gtest=${GTEST_INSTALL} --install-sandbox=${PLOUD_INSTALL} test
