language: cpp

# Use container-based infrastructure
sudo: required
services:
  - docker

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - GTEST_INSTALL=${TRAVIS_BUILD_DIR}/install-gtest
    - PLOUD_INSTALL=${TRAVIS_BUILD_DIR}/install-ploud
    - FFMPEG_VERSION=2.7.6
    - FFMPEG_INSTALL=${TRAVIS_BUILD_DIR}/install-dependency
    - AVTRANSCODER_VERSION=0.10.0
    - AVTRANSCODER_INSTALL=${TRAVIS_BUILD_DIR}/install-avtranscoder


# This results in a 2×2 build matrix.
# Where the variables are: os / compiler

addons:
  apt:
    sources: ['boost-latest']
    packages:
    - scons
    - libboost1.55-all-dev
    - libsndfile1-dev
    - libqt4-dev

cache:
  # Caching Ubuntu packages
  apt: true

install:
  # Install dependencies
  - ./tools/travis/install_dependencies.sh

  # Install coverage tools
  - ./tools/travis/gcc.install.coverage.sh

before_script:
  # Install test ressources
  - ./tools/travis/install_ressources.sh

script:
  # Build and run tests
  - scons --mode=release --coverage --avtranscoder=${AVTRANSCODER_INSTALL} --ffmpeg=${FFMPEG_INSTALL} --gtest=${GTEST_INSTALL} --install-sandbox=${PLOUD_INSTALL} --qt-suffix=qt4 --ebu-test-essences=ebu_test_essences test

after_success:
  # Generate and upload coverage to coveralls
  - ./tools/travis/gcc.generate.coverage.sh
