language: cpp

# Use container-based infrastructure
sudo: required
services:
  - docker

os:
  - linux

compiler:
  - gcc
  - clang

env:
  global:
    - PLOUD_INSTALL=${TRAVIS_BUILD_DIR}/install-ploud
    - CI_NODE_TOTAL=2

# This results in a 2×2 build matrix.
# Where the variables are: os / compiler

addons:
  apt:
    sources: ['boost-latest']
    packages:
    - scons
    - libboost1.55-all-dev
    - libsndfile1-dev
    - libqt4-dev
    - libgtest-dev

cache:
  # Caching Ubuntu packages
  apt: true

before_script:
  - env | sort  
  - date -u
  - uname -a
  - lsb_release -a

script:
  - export QTDIR=/usr/share/qt4
  # Get test ressources
  - wget https://tech.ebu.ch/files/live/sites/tech/files/shared/testmaterial/ebu-loudness-test-setv04.zip
  - unzip ebu-loudness-test-setv04.zip
  - export EBU_LOUDNESS_TEST_SET_PATH=`pwd`
  # Build and run tests
  - scons -j${CI_NODE_TOTAL} --mode=release --install-sandbox=${PLOUD_INSTALL} test
